version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped

  celery-worker:
    container_name: celery-worker
    image: python:3.10-slim  
    command: celery -A core worker -l INFO
    depends_on:
      - rabbitmq
    volumes:
      - .:/app  
    working_dir: /app 
    restart: unless-stopped

  celery-beat:
    container_name: celery-beat
    image: python:3.10-slim  
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - rabbitmq
    volumes:
      - .:/app  
    working_dir: /app 
    restart: unless-stopped

  django:
    container_name: django-app
    image: python:3.10-slim  
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
    depends_on:
      - rabbitmq
    restart: unless-stopped
    working_dir: /app  

  django-create-superuser:
    image: python:3.10-slim
    container_name: django-create-superuser
    working_dir: /app
    volumes:
      - .:/app
    command: python manage.py createsuperuser --noinput --username admin --email admin@example.com
    depends_on:
      - django
    restart: "no"

volumes:
  rabbitmq_data:
