version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped
    labels:
      com.example.service: "rabbitmq"

  celery-worker:
    image: python:3.10-slim
    container_name: celery-worker
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "celery -A core worker -l INFO"]
    depends_on:
      - rabbitmq
    restart: on-failure

  celery-beat:
    image: python:3.10-slim
    container_name: celery-beat
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"]
    depends_on:
      - rabbitmq
    restart: on-failure

volumes:
  rabbitmq_data:
